package com.memksim.todo

import com.memksim.todo.domain.model.Task
import com.memksim.todo.domain.utils.enums.TaskState

val fakeUpcomingDtoList: List<Task> = listOf(
    Task(
        1,
        "dto1",
        "note...",
        "01.01.2023",
        "23:59",
        false,
        TaskState.SAME
    ),
    Task(
        2,
        "dto2",
        "note...",
        "01.01.2023",
        "23:59",
        false,
        TaskState.SAME
    ),
    Task(
        3,
        "dto3",
        "note...",
        "01.01.2023",
        "23:59",
        false,
        TaskState.SAME
    ),
    Task(
        4,
        "dto4",
        "note...",
        "01.01.2023",
        "23:59",
        false,
        TaskState.SAME
    ),
    Task(
        5,
        "dto5",
        "note...",
        "01.01.2023",
        "23:59",
        false,
        TaskState.SAME
    )
)

val fakeCompletedDtoList: List<Task> = listOf(
    Task(
        1,
        "dto1",
        "note...",
        "01.01.2023",
        "23:59",
        true,
        TaskState.SAME
    ),
    Task(
        2,
        "dto2",
        "note...",
        "01.01.2023",
        "23:59",
        true,
        TaskState.SAME
    ),
    Task(
        3,
        "dto3",
        "note...",
        "01.01.2023",
        "23:59",
        true,
        TaskState.SAME
    ),
    Task(
        4,
        "dto4",
        "note...",
        "01.01.2023",
        "23:59",
        true,
        TaskState.SAME
    ),
    Task(
        5,
        "dto5",
        "note...",
        "01.01.2023",
        "23:59",
        true,
        TaskState.SAME
    )
)

val fakeDto = Task(
    1,
    "dto1",
    "note...",
    "01.01.2023",
    "23:59",
    false,
    TaskState.SAME
)